### ISSUE TITLE
About adding features to RailsBricks / JRuby support

### ISSUE THREAD

**Issue by PragTob** [nicoschuele/railsbricks#62]
Hi there,

thanks for railsbricks. It'd be cool if one could configure the ruby version to JRuby and with that configuration also exclude gems that do not work with JRuby. No idea if currently some gems don't work with JRuby - but it's used by many so it seems very wortwhile to add :)

Cheers,
Tobi

**edited by @nicoschuele:** 

*This issue evolved into an open discussion on how to manage the RailsBricks project. Contributions to the discussion are welcome. I also changed the title from "JRuby support" to "About adding features to RailsBricks / JRuby support"*.

**Comment by nicoschuele** [comment]
Alright, it has been two weeks now since this discussion has been opened here and on Reddit. As there as been no other contribution to it, I decided to update the README in the *Contribute* section with:

> **Important**: before working on a new feature, contact me or open an issue on Github explaining what you'd like to implement. I'm trying to keep the maintenance of RailsBricks as easy and fast as possible so before accepting a feature or a PR, we need to make sure it will be maintained properly and within an appropriate timeframe.

I went the option 2 proposed by Zootboy above:

> You still just want to do your own thing, and you don't want to bother with all this collaboration nonsense. That's fine, just make it clear on the page that if people want to contribute back, they're gonna have to fork it and maintain it themselves. And hey, if you both use licenses that are compatible with it, you can easily cherry-pick from each others patches while maintaining separate forks.

It is motivated by a "time at hands" factor rather than "I do what I want" but ultimately, the result is the same: I will continue to maintain RailsBricks and update it as fast as possible alone until a better option (aka "some seriously motivated contributors") comes along.

**Comment by sebap** [comment]
Hi Nico,

I think what you did with railsbricks is awesome, so here is an idea,
thinking about your situation about people asking for features that you
dont have time to implement or support. Look at sideqik
https://github.com/mperham/sidekiq, this guy has an opensource version, and
a pro version, of the same gem. I am not sure if this model would work for
your project but if time is a factor because you have to pay your bills, a
good approach is to synchronize both, specially if you enjoy working for
your own product. Just a thought, maybe it helps.

happy new year

Seba

**Comment by nicoschuele** [comment]
@sebap : Actually, this is a good idea and I thought about it. But due to the time constraints highlighted above, I'm waiting to see if this initiative comes from the community rather than me :-)

Happy new year to you too!
